name: Creation brabch release
on:
  push:
    branches: [ develop ]
jobs:
  job1:
    name: Creation release and merge to master
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'RELEASE:') }}
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create release
      run: |
        git checkout -b release
        git push -f -u origin release
    - name: Merge develop -> release
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: release
    - name: Run tests
      id: run-tests
      run: |
        git checkout release
        python -m unittest -v tests/test_persona.py
    - name: Merge release -> main
      if: ${{ success() }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: release
        target-branch: main