name: Merge to develop
on:
  push:
    branches: 
      - 'features/**'
jobs:
  job1:
    name: Unit tests and merge to develop
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'DONE:') }}
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Merge develop -> feature
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}
    - name: Run tests
      id: run-tests
      run: python -m unittest -v tests/test_persona.py
    - name: Merge feature -> develop
      if: ${{ success() }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
