name: Continuous Integration
on:
  push:
    branches: [ develop ]
jobs:
  job1:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      id: run-tests
      run: python -m unittest -v tests/test_persona.py